"""Repository contracts (Protocols).

Services depend on these, never on the concrete SQLite classes (Dependency
Inversion). They are split into narrow Reader/Writer roles (Interface
Segregation): the report service receives only readers and *cannot* mutate.

Write methods take an opaque `conn` (the connection yielded by a Unit of Work),
so the same transaction spans every write in a use case. The connection type is
intentionally `Any` to keep the contract backend-agnostic.
"""

from typing import Any, Protocol


class PartnerReader(Protocol):
    async def get(self, identifier: str) -> dict | None: ...
    async def list_rows(
        self, kind: str | None, include_archived: bool, q: str | None
    ) -> list[dict]: ...


class PartnerWriter(Protocol):
    async def insert(self, conn: Any, partner: dict) -> None: ...


class ItemReader(Protocol):
    async def get(self, identifier: str) -> dict | None: ...
    async def list_rows(
        self, kind: str | None, include_archived: bool, q: str | None
    ) -> list[dict]: ...
    async def on_hand_by_warehouse(self, item_id: str | None) -> list[dict]: ...


class ItemWriter(Protocol):
    async def insert(self, conn: Any, item: dict) -> None: ...
    async def apply_valuation(
        self, conn: Any, item_id: str, qty_delta_milli: int, value_delta_minor: int, now: str
    ) -> None: ...


class WarehouseReader(Protocol):
    async def get(self, identifier: str) -> dict | None: ...
    async def list_rows(self, include_archived: bool) -> list[dict]: ...


class WarehouseWriter(Protocol):
    async def insert(self, conn: Any, warehouse: dict) -> None: ...


class StockReader(Protocol):
    async def moves(
        self,
        item_id: str | None,
        warehouse_id: str | None,
        date_from: str | None,
        date_to: str | None,
        limit: int,
        offset: int,
    ) -> tuple[list[dict], int]: ...
    async def on_hand(self, item_id: str, warehouse_id: str) -> int: ...


class StockWriter(Protocol):
    async def insert_move(self, conn: Any, move: dict) -> None: ...


class AccountReader(Protocol):
    async def get(self, identifier: str) -> dict | None: ...
    async def get_by_role(self, role: str) -> dict | None: ...
    async def list_rows(self, account_type: str | None, include_archived: bool) -> list[dict]: ...
    async def net_debit(self, account_id: str, as_of: str | None) -> int: ...
    async def trial_balance_rows(self, as_of: str | None) -> list[dict]: ...
    async def type_totals(
        self, account_type: str, date_from: str | None, date_to: str | None
    ) -> list[dict]: ...
    async def ledger_rows(self, account_id: str, date_to: str | None) -> list[dict]: ...


class AccountWriter(Protocol):
    async def insert(self, conn: Any, account: dict) -> None: ...


class JournalReader(Protocol):
    async def get(self, entry_id: str) -> dict | None: ...
    async def lines(self, entry_id: str) -> list[dict]: ...
    async def search(
        self,
        q: str | None,
        date_from: str | None,
        date_to: str | None,
        source_type: str | None,
        limit: int,
        offset: int,
    ) -> tuple[list[dict], int]: ...
    async def by_source(self, source_type: str, source_id: str) -> dict | None: ...


class JournalWriter(Protocol):
    async def insert(self, conn: Any, entry: dict) -> None: ...
    async def insert_line(self, conn: Any, line: dict) -> None: ...
    async def mark_reversed(self, conn: Any, original_id: str, contra_id: str) -> None: ...


class PurchaseReader(Protocol):
    async def get_order(self, identifier: str) -> dict | None: ...
    async def order_lines(self, po_id: str) -> list[dict]: ...
    async def get_line(self, line_id: str) -> dict | None: ...
    async def search_orders(
        self, supplier_id: str | None, status: str | None, limit: int, offset: int
    ) -> tuple[list[dict], int]: ...
    async def get_receipt(self, identifier: str) -> dict | None: ...
    async def receipt_lines(self, grn_id: str) -> list[dict]: ...
    async def receipts_for_order(self, po_id: str) -> list[dict]: ...
    async def get_bill(self, identifier: str) -> dict | None: ...
    async def bill_lines(self, bill_id: str) -> list[dict]: ...
    async def search_bills(
        self, supplier_id: str | None, status: str | None, limit: int, offset: int
    ) -> tuple[list[dict], int]: ...
    async def open_bills(self, as_of: str | None) -> list[dict]: ...


class PurchaseWriter(Protocol):
    async def insert_order(self, conn: Any, order: dict) -> None: ...
    async def insert_order_line(self, conn: Any, line: dict) -> None: ...
    async def set_order_status(self, conn: Any, po_id: str, status: str, now: str) -> None: ...
    async def add_received(self, conn: Any, line_id: str, qty_milli: int) -> None: ...
    async def add_billed(self, conn: Any, line_id: str, qty_milli: int) -> None: ...
    async def insert_receipt(self, conn: Any, receipt: dict) -> None: ...
    async def insert_receipt_line(self, conn: Any, line: dict) -> None: ...
    async def insert_bill(self, conn: Any, bill: dict) -> None: ...
    async def insert_bill_line(self, conn: Any, line: dict) -> None: ...
    async def settle_bill(
        self, conn: Any, bill_id: str, amount_minor: int, status: str, now: str
    ) -> None: ...


class SalesReader(Protocol):
    async def get_order(self, identifier: str) -> dict | None: ...
    async def order_lines(self, so_id: str) -> list[dict]: ...
    async def get_line(self, line_id: str) -> dict | None: ...
    async def search_orders(
        self, customer_id: str | None, status: str | None, limit: int, offset: int
    ) -> tuple[list[dict], int]: ...
    async def get_delivery(self, identifier: str) -> dict | None: ...
    async def delivery_lines(self, delivery_id: str) -> list[dict]: ...
    async def get_invoice(self, identifier: str) -> dict | None: ...
    async def invoice_lines(self, invoice_id: str) -> list[dict]: ...
    async def search_invoices(
        self, customer_id: str | None, status: str | None, limit: int, offset: int
    ) -> tuple[list[dict], int]: ...
    async def open_invoices(self, as_of: str | None) -> list[dict]: ...


class SalesWriter(Protocol):
    async def insert_order(self, conn: Any, order: dict) -> None: ...
    async def insert_order_line(self, conn: Any, line: dict) -> None: ...
    async def set_order_status(self, conn: Any, so_id: str, status: str, now: str) -> None: ...
    async def add_delivered(self, conn: Any, line_id: str, qty_milli: int) -> None: ...
    async def add_invoiced(self, conn: Any, line_id: str, qty_milli: int) -> None: ...
    async def insert_delivery(self, conn: Any, delivery: dict) -> None: ...
    async def insert_delivery_line(self, conn: Any, line: dict) -> None: ...
    async def insert_invoice(self, conn: Any, invoice: dict) -> None: ...
    async def insert_invoice_line(self, conn: Any, line: dict) -> None: ...
    async def settle_invoice(
        self, conn: Any, invoice_id: str, amount_minor: int, status: str, now: str
    ) -> None: ...


class PaymentReader(Protocol):
    async def list_for(self, document_type: str, document_id: str) -> list[dict]: ...


class PaymentWriter(Protocol):
    async def insert(self, conn: Any, payment: dict) -> None: ...


class SequenceWriter(Protocol):
    async def next_number(self, conn: Any, name: str) -> str: ...


class AuditReader(Protocol):
    async def list(
        self,
        action: str | None,
        actor: str | None,
        object_id: str | None,
        limit: int,
        offset: int,
    ) -> tuple[list[dict], int]: ...


class AuditWriter(Protocol):
    async def append(self, conn: Any, entry: dict) -> None: ...


class SettingsReader(Protocol):
    async def get(self) -> dict | None: ...


class QueryRunner(Protocol):
    async def select(self, sql: str) -> list[dict]: ...
